volumes:
  pg_data:

networks:
  scheduler:
    name: scheduler_space
    driver: bridge
    external: true

services:
  mq:
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    image: rabbitmq:management
    ports:
      - "${RMQ_NETWOTK_PORT}:${RMQ_NETWOTK_INNER_PORT}"
      - "${RMQ_UI_PORT}:${RMQ_UI_INNER_PORT}"
    networks:
      - scheduler
  db:
    image: "postgres:16"
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PORT: ${PG_INNER_PORT}
      POSTGRES_POOL: 10
    ports:
      - "${PG_PORT}:${PG_INNER_PORT}"
      - "5333:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - scheduler
  event:
    build:
      context: ./event_microservice
      dockerfile: Dockerfile
    env_file:
      - ./event_microservice/.env
    depends_on:
      - mq
      - db
    restart: always
    ports:
      - "${EVENT_PORT}:${EVENT_PORT}"
    networks:
      - scheduler
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env_container
    depends_on:
      - mq
      - db
      - event
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - scheduler
