volumes:
  pg_data:
  redis_data:

networks:
  scheduler:
    name: scheduler_space
    driver: bridge

services:
  mq:
    image: rabbitmq:management
    env_file:
      - .env_api
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    ports:
      - "${RMQ_NETWOTK_PORT}:${RMQ_NETWOTK_INNER_PORT}"
      - "${RMQ_UI_PORT}:${RMQ_UI_INNER_PORT}"
    networks:
      - scheduler
  db:
    image: "postgres:16"
    restart: always
    env_file: .env_api
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PORT: ${PG_INNER_PORT}
      POSTGRES_POOL: 10
    ports:
      - "${PG_PORT}:${PG_INNER_PORT}"
      - "5333:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - scheduler
  event:
    image: aleksti/event_med:latest
    env_file:
      - .env_api
    depends_on:
      - mq
      - db
    restart: always
    ports:
      - "${EVENT_PORT}:${EVENT_PORT}"
    networks:
      - scheduler
  api:
    image: aleksti/api_med:latest
    env_file:
      - .env_api
    depends_on:
      - mq
      - db
      - event
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - scheduler

  redis:
    image: "redis:6.2-alpine"
    restart: always
    env_file: .env_api
    volumes:
      - redis_data:/data
    networks:
      - scheduler

  bot:
    image: aleksti/bot_med:latest
    env_file: .env_api
    networks:
      - scheduler
    depends_on:
      - redis
      - mq
      - db
      - event
      - api
