volumes:
  pg_data:
  redis_data:

networks:
  scheduler:
    name: scheduler_space
    driver: bridge

services:
  mq:
    image: rabbitmq:management
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    ports:
      - "${RMQ_NETWOTK_PORT}:${RMQ_NETWOTK_INNER_PORT}"
      - "${RMQ_UI_PORT}:${RMQ_UI_INNER_PORT}"
    networks:
      - scheduler

  db:
    image: "postgres:16"
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PORT: ${PG_INNER_PORT}
      POSTGRES_POOL: 10
    ports:
      - "${PG_PORT}:${PG_INNER_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - scheduler

  redis:
    image: "redis:6.2-alpine"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - scheduler

  event:
    build:
      context: ./event_worker
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DEV: prod
      PG_HOST: db
      RMQ_HOST: mq
    depends_on:
      - mq
      - db
    restart: always
    ports:
      - "${EVENT_PORT}:${EVENT_PORT}"
    networks:
      - scheduler

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DEV: local_container
      HOST: "0.0.0.0"
      PG_HOST: db
      RMQ_HOST: mq
    depends_on:
      - mq
      - db
      - event
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - scheduler

  bot:
    build:
      context: ./
      dockerfile: tg_bot/Dockerfile
    env_file: .env
    environment:
      DEV: prod
      RMQ_HOST: mq
      # Переопределяем BASE_URL_API_PROD для Docker-окружения
      BASE_URL_API_PROD: "http://api:${PORT}/api"
    depends_on:
      - redis
      - mq
      - api
    restart: always
    networks:
      - scheduler
