"""qwer

Revision ID: 458b58035402
Revises:
Create Date: 2024-11-16 05:21:21.166218

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "458b58035402"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user",
    sa.Column("id", sa.BigInteger(), nullable=False),
    sa.Column("username", sa.String(length=64), nullable=False),
    sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
    sa.Column("first_name", sa.String(length=64), nullable=True),
    sa.Column("last_name", sa.String(length=64), nullable=True),
    sa.Column("registered_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
    sa.UniqueConstraint("tg_user_id"),
    )
    op.create_table("manager",
    sa.Column("id", sa.BigInteger(), nullable=False),
    sa.Column("name", sa.String(length=128), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("start_date", sa.DateTime(), nullable=False),
    sa.Column("finish_date", sa.DateTime(), nullable=False),
    sa.Column("timezone", sa.String(length=64), nullable=False),
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
    )
    op.create_table("regimen",
    sa.Column("id", sa.BigInteger(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("drug_time", sa.TIME(), nullable=False),
    sa.Column("supplement", sa.String(length=128), nullable=False),
    sa.Column("manager_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["manager_id"], ["manager.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("regimen")
    op.drop_table("manager")
    op.drop_table("user")
    # ### end Alembic commands ###
